root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/notification-service ./cmd/main.go"
bin = "./tmp/notification-service"
include_ext = ["go", "env"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true