// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// InboxRepository is an autogenerated mock type for the InboxRepository type
type InboxRepository struct {
	mock.Mock
}

// IsProcessed provides a mock function with given fields: ctx, messageID
func (_m *InboxRepository) IsProcessed(ctx context.Context, messageID string) (bool, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveProcessed provides a mock function with given fields: ctx, messageID, eventType, payload
func (_m *InboxRepository) SaveProcessed(ctx context.Context, messageID string, eventType string, payload []byte) error {
	ret := _m.Called(ctx, messageID, eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, messageID, eventType, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInboxRepository creates a new instance of InboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InboxRepository {
	mock := &InboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
